# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-04 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180604_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_discount',
            field=models.BooleanField(default=False, verbose_name='标记为打折商品'),
        ),
    ]
