# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-04 03:26
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180604_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_info',
            field=redactor.fields.RedactorField(verbose_name='商品详情'),
        ),
    ]
