# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-05 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180604_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='title',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='颜色标题'),
        ),
    ]
