# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-05 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_color_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='广告标题')),
                ('link', models.CharField(blank=True, max_length=128, null=True, verbose_name='广告链接')),
                ('is_terminal', models.BooleanField(default=False, verbose_name='是否终端显示')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/ad/img/', verbose_name='广告图片')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/ad/video/', verbose_name='广告视频')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='该广告在广告列表中的顺序', verbose_name='顺序')),
                ('remarks', models.TextField(blank=True, help_text='请输入备注、描述等', null=True, verbose_name='备注、描述')),
            ],
            options={
                'verbose_name': '轮播广告',
                'verbose_name_plural': '轮播广告',
                'ordering': ['order'],
            },
        ),
    ]
