# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-05 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_advertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='is_terminal',
        ),
    ]
