# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-06 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20180606_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=128, verbose_name='联网方式')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='展示顺序', verbose_name='顺序')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': '商品联网方式',
                'verbose_name_plural': '商品联网方式',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='channel',
        ),
        migrations.AddField(
            model_name='mode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_product', to='product.Product', verbose_name='所属商品'),
        ),
    ]
