# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-05 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20180605_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_received',
        ),
    ]
