# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-06 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20180606_1036'),
        ('payment', '0003_remove_order_is_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_goods',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_mode', to='product.Mode', verbose_name='商品联网方式'),
        ),
    ]
