# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-09 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_goods_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1, verbose_name='商品数量'),
        ),
    ]
