# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-11 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_payment',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('1', '未支付'), ('2', '已支付'), ('3', '已发货'), ('4', '已收货')], default='1', max_length=1, null=True, verbose_name='订单状态'),
        ),
    ]
