# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-04 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'ordering': ['-update_time'], 'verbose_name': '商城用户', 'verbose_name_plural': '商城用户'},
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='re_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='收货人电话'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='receiver',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='收货人'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='用户电话号码'),
        ),
    ]
