# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-13 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='用户姓名'),
        ),
    ]
